# ─── PACKAGING ────────────────────────────────────────────────────────────────
# pymysql is not included in the AWS Python runtime: it is installed via pip
# into a temporary folder, then bundled with the handler into a zip archive.
# The build.sh script performs this step and can be executed manually before terraform apply.
# Here we assume the zip file is already available (generated by script/build.sh).

data "archive_file" "lambda" {
  type        = "zip"
  source_dir  = "${path.module}/../script/build"
  output_path = "${path.module}/../script/lambda.zip"
}

# ─── IAM ──────────────────────────────────────────────────────────────────────

data "aws_iam_policy_document" "lambda_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "lambda" {
  name               = "${var.project_name}-lambda-role"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume.json
}

# CloudWatch Logs permissions
resource "aws_iam_role_policy_attachment" "lambda_basic" {
  role       = aws_iam_role.lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# ENI management inside the VPC.
# Without this policy, Lambda cannot create network interfaces
# in private subnets and deployment will fail.
resource "aws_iam_role_policy_attachment" "lambda_vpc" {
  role       = aws_iam_role.lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
}

# ─── CLOUDWATCH LOGS ─────────────────────────────────────────────────────────

resource "aws_cloudwatch_log_group" "lambda" {
  name              = "/aws/lambda/${var.project_name}-function"
  retention_in_days = 7
}

# ─── LAMBDA ───────────────────────────────────────────────────────────────────
#
# vpc_config: private subnets only.
# A Lambda function in a public subnet has no real internet access (no public IP
# on its ENI) and cannot properly reach private resources either.
# The private subnet + NAT pattern is the standard production setup.
#
# AWS-created ENIs can be found in EC2 → Network Interfaces
# with the description "AWS Lambda VPC ENI - <function-name>".

resource "aws_lambda_function" "main" {
  function_name = "${var.project_name}-function"
  role          = aws_iam_role.lambda.arn
  handler       = "handler.lambda_handler"
  runtime       = "python3.12"

  filename         = data.archive_file.lambda.output_path
  source_code_hash = data.archive_file.lambda.output_base64sha256

  timeout     = 30   # RDS may be slow on first request (VPC cold start)
  memory_size = 256

  vpc_config {
    subnet_ids         = module.vpc.private_subnet_ids
    security_group_ids = [aws_security_group.lambda.id]
  }

  environment {
    variables = {
      DB_HOST     = aws_db_instance.mysql.address
      DB_PORT     = tostring(aws_db_instance.mysql.port)
      DB_NAME     = var.db_name
      DB_USER     = var.db_username
      DB_PASSWORD = var.db_password
    }
  }

  depends_on = [
    aws_iam_role_policy_attachment.lambda_basic,
    aws_iam_role_policy_attachment.lambda_vpc,
    aws_cloudwatch_log_group.lambda,
  ]

  tags = { Name = "${var.project_name}-function" }
}